# Generated by Django 2.2 on 2019-04-04 18:45

from django.db import migrations, models
##장고 database 테이블  

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=200)),
                ('dates', models.DateTimeField(verbose_name='dates')),
            ],
        ),
        migrations.CreateModel(
            name='Musinsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('dates', models.DateTimeField(verbose_name='dates')),
                ('rank', models.BigIntegerField()),
            ],
        ),
    ]
