# Generated by Django 2.2 on 2019-04-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=10)),
                ('mentions', models.BigIntegerField()),
                ('reviews', models.BigIntegerField()),
            ],
        ),
    ]
