# Generated by Django 2.2 on 2019-04-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_mention'),
    ]

    operations = [
        migrations.AddField(
            model_name='mention',
            name='keyword',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
    ]
