# Generated by Django 2.2 on 2019-05-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_instagram_association_musinsa_association'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram_sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default='DEFAULT VALUE', max_length=200)),
                ('year', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=200)),
                ('pos', models.BigIntegerField()),
                ('neg', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Musinsa_sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default='DEFAULT VALUE', max_length=200)),
                ('year', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=200)),
                ('pos', models.BigIntegerField()),
                ('neg', models.BigIntegerField()),
            ],
        ),
    ]
